### ISSUE TITLE
missed some extensions

### ISSUE THREAD

**Issue by iMohammadd** [aschmelyun/docker-compose-laravel#1]
hi  
where is `gd mcrypt curl xml` extensions?

**Comment by aschmelyun** [comment]
`curl` and `xml` are installed automatically with the PHP image being pulled in (7.2fpm-alpine). Laravel hasn't required `mcrypt` since 5.1, and I don't believe has ever required the `gd` library.

However, if you would like to install these on your own, modifying the Dockerfile's 3rd line to something like:

```
RUN docker-php-ext-install pdo pdo_mysql mcrypt
```

could help your case. However, doing some quick research it seems that the gd extension needs a little more work using this: https://github.com/mlocati/docker-php-extension-installer.
