### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by mmaaarten** [aschmelyun/docker-compose-laravel#120]
When i upped my docker and im trying to open the browser based on my nginx its giving me a 500 error.

Can someone help me out?
screen: https://prnt.sc/1v0k2ne

Running: Mac osX - Big Sur

**Comment by mmaaarten** [comment]
@rabin-io this is the only log i get: 172.20.0.1 - - [07/Oct/2021:08:27:19 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"

**Comment by aschmelyun** [comment]
Hey everyone! Sorry about that, this was fixed with this commit: https://github.com/aschmelyun/docker-compose-laravel/commit/14d1c361325fa510bf03cf8ce0dd4b4ea4b8cd2a

The problem was related to what @riaandreyer said above, but it's not directly a Laravel issue. Laravel 8 does have some packages that depend on PHP 8, but they also have compatibility for 7.3+7.4, it just depends on what version you're using to install Laravel with.

Well, the Composer container that was being used upgraded to PHP 8, and so when using it to install a Laravel app or packages for it, it assumes you were running on PHP 8 and set the dependencies based on that version.

Additionally, the PHP errors weren't being logged, so I added that too.
