### ISSUE TITLE
[Q] Serving this without Nginx?

### ISSUE THREAD

**Issue by heychazza** [aschmelyun/docker-compose-laravel#127]
Hi,

I'm looking to run this via the following;

**Nginx** is hosted on the droplet itself, and does a proxy pass to the container which has the laravel app.

What would I need to tweak to this, to be able to do so? Without going **Nginx** -> **Nginx**.

**Comment by aschmelyun** [comment]
Hey @heychazza 

I'm not sure about that as I haven't come across a use case similar to this. I'd say that you _should_ be able to use the exposed `9000` port of the php container and just proxy-pass `127.0.0.1:9000` instead of what's in the nginx container now.

I know there's also a few methods of passing through a docker socket to/from the machine running the compose stack and using that as a pass-through.

Hope any of this helps!
