### ISSUE TITLE
Slow on Mac OS

### ISSUE THREAD

**Issue by brainlet-ali** [aschmelyun/docker-compose-laravel#25]
I followed your instructions both on Windows and Mac. It worked like charm on Windows but on Mac both CLI (like php artisan inspire) and site rendering time in browser are really slow. Do you think adding a ubuntu-alpine layer on top will help ?

**Comment by paulocastellano** [comment]
Docker is very slow at Mac... i have same problem.

But on Dell@ubuntu is very fast.

**Comment by netojose** [comment]
Docker on the Mac is [slow](https://github.com/docker/for-mac/issues/77), at the time of writing.  The problem is [older than March 2016 - as it’s a such a long-running issue](https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076)

**Comment by netojose** [comment]
Hey, I'm here again. Really, it's very slow.
I installed this and, a simple request on a Laravel fresh install, a single endpoint was taking more than 2 seconds.

I used this other solution https://laradock.io/ And I got to make the same request 46X faster

**Comment by aschmelyun** [comment]
If you need a fully robust environment, https://laradock.io is a great choice. However, this repo and the accompanying tutorial for it on YouTube was designed to show you how to create a bare-bones dev environment for Laravel using Docker from scratch.

The reason that Docker is slow on MacOS is due to a virtualization layer that's in between it and your computer's file system. You can use something like `:delegated` on each of your volumes to help speed up response time by a large margin. 

See the following article on Docker's website for more info: https://docs.docker.com/docker-for-mac/osxfs-caching/
