### ISSUE TITLE
Too many containers

### ISSUE THREAD

**Issue by filipbekic01** [aschmelyun/docker-compose-laravel#37]
I see that on Github you created container for each tool such as npm, composer etc. What do you thinking about creating single container with all those tools in? For example, you can easly merge php and composer containers. What's better solution tho?

**Comment by oranges13** [comment]
It's easier to have a composer specific container so you can use `docker run` instead of trying to use that on your app image. Plus you can add or change your composer image at will without having to rebuild your app container.

**Comment by filipbekic01** [comment]
I see but let's take php and artisan for an example.

First we build custom php image with extensions from alpine which is fine. However, then we build whole new (same) image but adding `php artisan` as entrypoint. If i understood right, we end up having 2 exactly same images where artisan has entrypoint. Am i right? Maybe i got something wrong here.

I agree that it's easier to just write `docker run artisan ...` but i just wanted to be sure i understand the concepts right.

**Comment by aschmelyun** [comment]
It's less about what's an easier or simpler solution, and more about what the Docker ideology says is the better way. In most cases, you should separate out your services into containers that are single-use.

In this repo's example, our `php` container handles the compiling of PHP code, while the `composer` container handles incoming commands from the terminal to use the Composer package manager.

Additionally, because the `composer` container is accessed through the command line, and is it's own container, we can spin up multiple at once, each one getting it's own amount of shared resources, to perform a specific action. If one of them freezes up while working on something, it won't affect the rest of the application's performance since it's isolated.

Hope that helps!
