### ISSUE TITLE
Permission problems on Linux

### ISSUE THREAD

**Issue by Flayshon** [aschmelyun/docker-compose-laravel#5]
I tried running this on Linux, but the Laravel welcome page won't load and a permission exception is thrown unless I do

```
sudo chmod 777 -R storage/
sudo chmod 777 -R bootstrap/cache/
```

...which I'm not sure if it's the safest option.

This seems to happen because _"unlike on Mac or Windows, Docker on Linux has no layer of virtualization. As a result of this (and how containers work in general), operations run within the Docker container on shared files are affected by the owner and permissions of those files"_ https://vessel.shippingdocker.com/docs/linux-permissions/

The containers you defined are running as root, while the files created by composer belong to my host user (flayshon:flayshon). Is there something I can add to the Dockerfile to make this work without the chmod workaround?

**Comment by aschmelyun** [comment]
Hey @Flayshon!

It's funny that you mentioned this, as I spent today working on a new version of the docker-compose script that adds more functionality, and fixes permissions/filesystem issues like this. It's not yet complete, but check out the v2 branch of this repo and the docker-compose.yml file in it. Specifically the `composer` container.

If you add that in, and instead of running composer locally on your system to get a Laravel app running, run this command instead:

`docker-compose run --rm composer create-project laravel/laravel .` it should create the app using Docker's filesystem and permissions instead of the host machine. 

There's a follow-up video that I'm working on now set to come out probably this Friday, where I go into more detail.

**Comment by Flayshon** [comment]
Using a composer container like this kinda works, but then all the files belong to the containers root user now, so I ended up having to use sudo in other to modify them. I'm also having trouble figuring out how to use this with an already existing laravel project. Do I have to use `docker-compose run/exec` to clone a repo? Do I need a Git container? It never ends hahaha

**Comment by aschmelyun** [comment]
Totally understand! I'll try to come up with a good flow for both new and existing applications, and hopefully that'll help with any issues. I'll update this thread as soon as it's out!

**Comment by Flayshon** [comment]
It got a little better when I added the user option (-u --user) passing the host user uid:gid

```
docker-compose run --rm --user `id -u`:`id -g` composer create-project laravel/
laravel .
```

Now all my files belong to the host user instead of root. Only strange thing is that I had to `docker-compose down` and them `docker-compose up -d` again for it to work. Weird...but at least it works.

I also don't know how the whole thing is gonna behave if I commit the code with this user:group setting and try to edit the files on another work station, but I'll have access to another computer I can test this next week :)

**Comment by Flayshon** [comment]
forgot to mention I had to add this to the php container

```yml
user: 1000:1000
```

if I don't, when I try to load the app for the first time, the log/cache files I mentioned in the first comment won't get generated with the proper permission settings and laravel throws an exception.
