### ISSUE TITLE
Very long TTFB times

### ISSUE THREAD

**Issue by tusamni** [aschmelyun/docker-compose-laravel#57]
I loaded the Docker setup, installed Statamic 3 and I'm seeing 7-10 second time to first byte delays.

![Screenshot_1](https://user-images.githubusercontent.com/9271145/88716978-765b3b00-d0e5-11ea-9b5b-50b9a2234f2d.jpg)

Anyone else experiencing this?

**Comment by tusamni** [comment]
Update, I tested loading an index.html with only HTML, no issues.

I then changed it to index.php and did a simple echo, no TTFB issues either.

I'll keep investigating.

**Comment by tusamni** [comment]
Not sure if it helps, but here's the Laravel timing

![Screenshot_2](https://user-images.githubusercontent.com/9271145/88718363-7d834880-d0e7-11ea-8864-58416273ed81.jpg)

**Comment by SomePlayer** [comment]
I googled around and its docker WSL2 problem, and they are working on it. IO operations are slow to/from the container. Some said using WSL 1 was faster, but on Windows 10 Home you cant use that.

I read it some days ago, so forgive me for not having a link.

**Comment by aschmelyun** [comment]
Hey all,

I've seen this issue come up a few times for different Laravel-based platforms, so I might end up adding to the README because of it. 

Long response times are unfortunately a caveat of using volumes on non-Linux systems. Because on Windows and MacOS, there's a virtualization layer between the container and your system, it can take a while to get responses back from the server.  Especially with something like Statamic, which uses a lot of file read/writes. 

You can improve this by adding `:delegated` to your volumes, which allows them to recognize the container as the source of truth. It's not perfect,  but should help.

See this link for more details, and I'll be publishing a video in the coming weeks that address this:  https://docs.docker.com/docker-for-mac/osxfs-caching/
