### ISSUE TITLE
Question: Adding an existing laravel project from github

### ISSUE THREAD

**Issue by SomePlayer** [aschmelyun/docker-compose-laravel#60]
Due to windows constantly reverting my changes to my host file, I finally decided to move away from WAMP for my laravel project. 

I simply gitted my exsiting project into the _/src_ directory.
But something seems to be a miss. Because _docker-compose up -d --build site_ will choke on **node_modules** and **vendor** directory when I make changes that require a rebuild.

I tried .dockerignore but it did not help.

Am I suppose to maybe add my laravel git to the build image container?

Does anyone have some magic for docker-compose.yml ?

This workaround does work: https://github.com/aschmelyun/docker-compose-laravel/issues/33

**Comment by aschmelyun** [comment]
Because of the differences that your previous environment has to this one, you might see errors using the in-Docker Composer and npm containers. Usually if I'm bringing a project I've already worked on into this local Docker environment, I'll do the following:

1. Remove the `node_modules` directory, `vendor` directory, and the `package-lock.json` file from the `src` directory.
2. Run `docker-compose run --rm composer install` from the project root, using Docker to install the composer dependencies.
3. Run `docker-compose run --rm npm install` from the project root, using Docker to install the npm dependencies.
4. Run `docker-compose run --rm npm run dev` to compile any assets using the Docker pipeline.

After doing that, you *should* be good to go without having to do those steps again, as long as you continue using the local Docker environment.

**Comment by techguydev** [comment]
I am having a similar problem.

I would like to add this docker file to my local environment, although I am just getting started with Docker.

For existing project would you add this Docker file to Git?, or would you just leave it for local machine?

if I would like to add it to git where can I can the src location so  I do not add the Laravel files inside src but add the Docker file to the root?

Thanks
