### ISSUE TITLE
How to run an artisan command from inside webpack.mix.js?

### ISSUE THREAD

**Issue by addorange** [aschmelyun/docker-compose-laravel#65]
Hi, thanks a lot for this nice introduction to use docker in Laravel.

I managed to set it up, but now I am basically struggling to use an artisan command run by webpack.mix.js. 

`mix.copy('resources/js/Mixins/localizations.js', 'public/js/localizations.js')
    .js('resources/js/app.js', 'public/js/app.js')
    .postCss('resources/css/app.css', 'public/css', [
        require('tailwindcss'),
    ])
    .tailwind('./tailwind.config.js')
    .webpackConfig({
       output: { chunkFilename: 'js/[name].js?id=[chunkhash]' },
       resolve: {
           alias: {
               vue$: 'vue/dist/vue.runtime.esm.js',
               '@': path.resolve('resources/js'),
           },
       },
       plugins: [
           new WebpackShellPlugin({onBuildStart:['php artisan lang:js resources/js/Mixins/localizations.js --quiet'], onBuildEnd:[]})
       ]
    })
    .babelConfig({
        plugins: ['@babel/plugin-syntax-dynamic-import'],
    });
`

I just wonder how to use the onBuildStart to call the corresponding artisan container as it always throws an error like 

`Error: spawn php ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn php',
  path: 'php',
  spawnargs: [
    'artisan',
    'lang:js',
    'resources/js/Mixins/localizations.js',
    '--quiet'
  ]
}`

Would be nice to hear from someone, who may have resolved this kind of issue.

Cheers,

Christian

**Comment by aschmelyun** [comment]
Hey @addorange 

If you're running `npm run dev` locally (not through Docker) then it would be as simple as swapping out your `php artisan lang:js` for `docker-compose run --rm artisan lang:js`. 

However,  if you're using `docker-compose run --rm npm run dev` for your asset compilation, that's going to be hard (if not impossible) to complete. Because npm is running isolated inside of a container,  it doesn't have any access to the php container except through the network. Which you can't use to run commands over.

I'll do some more research and digging, but on the surface level your best bet would be to possibly create a separate service for compiling your language and have it fire off with a CURL request to it that you can do after the npm build.
