### ISSUE TITLE
nginx.dockerfile missing command

### ISSUE THREAD

**Issue by iacobfrunze** [aschmelyun/docker-compose-laravel#95]
Please add this line:

**RUN rm -f /etc/nginx/conf.d/default.conf**

before these lines:
https://github.com/aschmelyun/docker-compose-laravel/blob/814e29a677be17bb1129dbad9d63d14e922da621/nginx.dockerfile#L3-L4

for some reason, the file already exists at build time and it won't replace the file, it simply starts the server with the builtin config and the default root path ... awful piece, lost a lot of time debugging.

**Comment by aschmelyun** [comment]
@iacobfrunze This should be fixed in the newest update! Thanks for finding this, according to [this StackOverflow answer](https://stackoverflow.com/a/40896066), removing the filename from the to folder in the `ADD` commands accomplishes the same thing, and should be how this was implemented in the first place.
